/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.yourcompany.yourproject;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
